### PR TITLE
Use arXiv API, enable all arXiv categories, scan abstract, rename to arxiv-scan

### LINKED ISSUE #2: only today's listings or those of a whole month can be shown
what other listings are possible from the HTML listings on astro-ph? Can they be implemented?

### LINKED ISSUE #6: [enhancement] Using arxiv.org API or RSS feed instead of regex HTML parsing
Currently the astro-ph listings are queried on their HTML interface and "parsed" using regex. This seems fragile and error-prone, (this is slightly alleviated by the fact that the arxiv.org interface changes rarely, but still).

The better solution would be to use the [arxiv.org API](https://arxiv.org/help/api/basics) and/or the [RSS feeds](https://arxiv.org/help/rss).
The API result and RSS feeds have a clearly defined XML structure, which can be really parsed, and should contain the same information as the HTML. This should also make it easier to allow for the same functionality on other archives on arxiv.org other than astro-ph.

But the details of this are not yet clear to me, one would need to find the right API query or RSS feed to match the submissions shown on astro-ph recent (and etc.).
Maybe the [form interface](https://arxiv.org/form/astro-ph) is also useful for this, but we would need to find out if all form queries can be translated into API queries.

What are your thoughts on this?

### LINKED ISSUE #12: Aliases to run the script from a shell
Currently there are three aliases that can be used to call the program:
- scan_astro-ph
- scan_astroph
- astroph-scan

This can be a bit cumbersome for Tab-completion in the shell, as one gets stuck where multiple option to continue exist (at several points in case of the first two aliases).

Maybe we should agree on a single command to invoke scan_astro-ph and drop the aliases.

### LINKED ISSUE #13: [enhancement] Generalize topic selection from arXiv.org
Currently only papers from astro-ph.EP are scanned.
It would be nice to have this configurable, such that a list of topics from arXiv can be scanned.

Should be implemented together with #6.

### LINKED ISSUE #15: Include abstract in rating calculation
With the new parsing implementation using the API (#14) the abstract is now also part of the `Entry` object and can therefore be easily scanned for keywords.

This brings up the question: does it make sense to introduce an weight factor between title and abstract? Keywords which occur in the title arguably carry more weight than an occurrence in the abstract.

An author weight could also be used, but the same effect can also be achieved by the user by setting the ratings of authors generally higher/lower than for keywords.

### PR DESCRIPTION
**Pull request by Simske**
This adds:
- using arXiv API instead of parsing HTML
- enable arXiv categories other than astroph, with flexible selection in config file
- abstract is also scanned for keywords
- more flexible date range selection

Todo:
- [x] Extend Entry for extra fields needed
- [x] Implement API parsing using feedparser
- [x] Customize main program flow for new parser
- [x] Add category options
- [x] Add abstract into evaluation (Closes #15)
- [x] Extend date selector
- [x] Rename package to `arxiv-scan` and change entrypoints accordingly (Closes #12)
- [x] Update Readme

Installation of this version:
```
pip install --upgrade git+https://github.com/simske/scan_astro-ph.git@api
```
For new configuration options check the [Readme in this branch](https://github.com/Simske/scan_astro-ph/blob/api/README.md).

Closes #6
Closes #13 
Closes #2

### CODE REVIEW

**Comment by matiscke** [comment]
I noticed that the option to specify a date is broken: `scan_astro-ph --date 2021-06` gives a syntax error.

**Comment by matiscke** [comment]
> I noticed that the option to specify a date is broken: `scan_astro-ph --date 2021-06` gives a syntax error.
@Simske any ideas where the problem might lie? I think the search of abstracts from a specific date is important functionality.

**Comment by Simske** [comment]
> I noticed that the option to specify a date is broken: scan_astro-ph --date 2021-06 gives a syntax error.
The syntax error comes from the way we parse the config parameters (basically it tries to parse the  date as an `int`, and fails at the `-`. I already fixed this.

> I think the search of abstracts from a specific date is important functionality.
The ArXiv API is unfortunately very rudimentary, and doesn't include any filtering by date.

I have an idea for a workaround: as arXiv ids follow the format `arXiv:YYMM.number` ([Reference](https://arxiv.org/help/arxiv_identifier)), we use this to find all papers from am month.

**Comment by Simske** [comment]
I misunderstood this: the goal is not to get the submissions from a specific date, but to go backwards in time to a specified date.
This is now implemented again, as everything but the interface was already there.

**Comment by matiscke** [comment]
@Simske can we merge this into 'main' or would you like to implement the renaming of the package first? Do I risk to break something if I do the renaming myself?

**Comment by Simske** [comment]
I will do a rebase, as #11 is merged now to keep the history cleaner.

As for the naming: what did we land on for a new name?
I vote for `arxiv-scan`.

**Comment by matiscke** [comment]
Some catchy pun would be even better, maybe something that sounds a bit like "Arxive" or includes parts of it. But I'm too uncreative right now...

Go ahead with `arxiv-scan` if you like.

**Comment by Simske** [comment]
I have now rebased everything on main, and changed the name to `arxiv-scan` for now.

Configfiles with the old name will still be found, but the new default locations reflect the naming change.

> Some catchy pun would be even better, maybe something that sounds a bit like "Arxive" or includes parts of it. But I'm too uncreative right now...
I agree, but I also have no good idea right now. We should maybe figure this out before renaming this repository and publishing the package to [PyPi](https://pypi.org/).

But  this PR can be merged now.

**Comment by matiscke** [comment]
image

**Comment by Simske** [comment]
The install command from the README only works after it is merged.
If you want to install from this PR you can use
```
pip install --upgrade git+https://github.com/simske/scan_astro-ph.git@api
```

**Comment by matiscke** [comment]
oh, yes this makes a lot of sense. I tested this branch superficially, everything seems to still work like a charm! 

@Simske how about renaming this gh repository to `arxiv-scan` as well? Developers have to change their remote locally, but at this point it should not affect anyone else.

**Comment by Simske** [comment]
> how about renaming this gh repository to arxiv-scan as well? Developers have to change their remote locally, but at this point it should not affect anyone else.
Yes I agree. But I would only do this if you want to keep the name as `arxiv-scan`.

**Comment by matiscke** [comment]
At any case I think it's more likely that we keep `arxiv-scan` than `scan_astro-ph`.

**Pull request merged**
