### PR TITLE
Restructuring and code cleanup

### LINKED ISSUE #7: [refactor] Python 2 support, dependencies, code structure
While looking over the code, a few things caught my eye, but I didn't want to open an issue for each of these, so here they are all in one:
- Some parts of the code try to be compatible with both Python 3 and Python 2 (e.g. future imports in `scan_astroph.py`). Should this package be compatible with Python 2? In my opinion this is not necessary, considering Python 2 maintainance has ended on 2020-01-01. 
- For CLI argument parsing the [deprecated module `optparse`](https://docs.python.org/3/library/optparse.html?highlight=optparse#module-optparse) is used, this should be switched to the newer [`argparse`](https://docs.python.org/3/library/argparse.html#module-argparse) (also in the Python standard library). The interface is very similar, and should be fast to switch
- Instead of the manual `debug_print` function, the logging module could be used, coupled with a verbosity argument on the CLI (`-v`, `-vv`, `-vvv` depending on log level)
- For colored output in the terminal the package [`termcolor`](https://pypi.org/project/termcolor/) is used. The last release of `termcolor` is from 2011, maybe there are more up to date packages out there (or not, I haven't checked yet).  
  Also: I haven't declared termcolor a dependency in the package installer (#5), this should be done when this is resolved.
- It can be nice to have a consistent code style in the project, I personally use the [black](https://github.com/psf/black) as formatter and [isort](https://pycqa.github.io/isort/) for import sorting.  
  To enforce this on the repository the tool [pre-commit](https://pre-commit.com/) can be used, which can run black and isort (and others) on commit (if the user installs it), and can also be configured with Github actions.

Obviously I don't want to step on anyone's toes, these were just some observations I made.

Not all of these need to be addressed, but I thought I just throw this out there to see what your thoughts on this are.

I am happy to work on any/all of them, most of them don't require a lot of work (and have nothing to do with functionality).

### PR DESCRIPTION
**Pull request by Simske**
Closes #7

Todo-list:
- [X] Modularizing / renaming functions
- [X] Replace deprecated `optparse` with `argparse` for CLI argument parsing
- [X] General code cleanup
- [x] Add logging (most debug_prints statements were removed during code cleanup)
- [x] Check colors in terminal output

### CODE REVIEW

**Comment by Simske** [comment]
Summary:
- `scan_astroph.py` was split up into multiple modules, some funciton names were changed for clarity
- CLI arguments are now parsed with `argparse`, because of the deprecation of `optparse`
- The code was generally cleaned up, all `debug_print` statements were removed, some code was refactored
- The output function has not been refactored, this may be a task for the future, but `termcolor` was added as dependency
- New logging flag was setup (`--log {info,debug`) which sets the loglevel for the [logging module](https://docs.python.org/3/library/logging.html?highlight=logging#module-logging). No logging messages were inserted, this can be done when necessary

**Comment by Simske** [comment]
This now ready to merge

**Comment by matiscke** [comment]
great @Simske , I'm currently reviewing this PR and it looks all good. Give me a bit to test this branch some more under realistic conditions.

**Review by matiscke — COMMENTED** [review]
image

compared to the current version, this branch considers keywords also when they are part of a larger word. In this specific case, it would be a false positive (the actual keyword `disc` was detected in the unrelated word `discoveries`).  However, I'm not sure if this is such bad behavior, as it keeps the user from having to specify all forms of a keyword (e.g., plurals). For instance, a keyword `planetesimal` would be detected even if the title contains only `planetesimal**s**`.

**Comment by Simske** [comment]
The behavior isn't related to any changes I made. I just compared the output of the refactored version with the the last version before my first commit (c8c2cf9), and the output is exactly the same.


I agree though that this is not a bad behavior, I expect the number of false positives to be much lower than false negatives, especially if the keywords are more specific.

**Comment by matiscke** [comment]
> The behavior isn't related to any changes I made. 
Strange, I could swear it didn't show up in the main branch. Anyways, I think we should keep this as is _for the keywords_.

For the favorite authors, though, this might be problematic. During testing, I noticed (thanks to the great new color highlighting!) that authors are counted that I have never heard of. It took me a while to figure out what is wrong, but here is a  pathological example:
image

The string `he`, which is an author name in my author list, is found in `Michele`. 

I changed that part of the code to search for complete words using `re.search()`.

**Pull request merged**
