### PR TITLE
Made scripts installable as pip Package

### PR DESCRIPTION
**Pull request by Simske**
This adds the necessary installer files to make this installable with `pip`.

The installation uses [setuptools_scm](https://github.com/pypa/setuptools_scm), with this the package version is extracted from git tags (and the distance in commits from the last tags for development versions).

The script can now be invoked with entrypoints (from anywhere in the filesystem). For now a few aliases are defined:
 - `scan_astro-ph`
 - `scan_astroph`
 - `astroph-scan`
Eventually only one of them should stay, but this should be discussed.  
The wordcounter script can be invoked with `scan_astro-ph.wordcounter`.

If for some reason entrypoints don't work an a system, they can also be invoced as modules:
- `python -m scan_astroph`
- `python -m scan_astroph.wordcounter`

### CODE REVIEW

**Comment by matiscke** [comment]
Thanks for the effort, @Simske! Just so I understand correctly, the package would be installable via `pip` from github, without necessity to publish it on PyPI?

**Comment by matiscke** [comment]
I tested installing via `setup.py` from your branch and got the following error message: 

`Traceback (most recent call last):
  File "/Users/schlecker/opt/anaconda3/bin/scan_astroph", line 33, in <module>
    sys.exit(load_entry_point('scan-astroph==0.1.dev20+g82d800c', 'console_scripts', 'scan_astroph')())
  File "/Users/schlecker/opt/anaconda3/bin/scan_astroph", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/scan_astroph-0.1.dev20+g82d800c-py3.8.egg/scan_astroph/__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'scan_astroph._version'
`
It seems there is still some issue with the version handling?

**Comment by Simske** [comment]
> Thanks for the effort, @Simske! Just so I understand correctly, the package would be installable via `pip` from github, without necessity to publish it on PyPI?

Yes exactly, only dependency is that git has to be also installed.

The installer can also be used to install it from a local directory (with `pip install path/to/package`), and in editable mode (`pip install -e path/to/package`), so you can run it as a package from your development directory.

**Comment by Simske** [comment]
> I tested installing via `setup.py` from your branch and got the following error message:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/schlecker/opt/anaconda3/bin/scan_astroph", line 33, in <module>
>     sys.exit(load_entry_point('scan-astroph==0.1.dev20+g82d800c', 'console_scripts', 'scan_astroph')())
>   File "/Users/schlecker/opt/anaconda3/bin/scan_astroph", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/Users/schlecker/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/Users/schlecker/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/scan_astroph-0.1.dev20+g82d800c-py3.8.egg/scan_astroph/__init__.py", line 1, in <module>
> ModuleNotFoundError: No module named 'scan_astroph._version'
> ```
> 
> It seems there is still some issue with the version handling?

For the version handling `setuptools_scm` is used, it writes the current version into `_version.py` when the installer runs. Apparently that file wasn't created in your case, I'm not sure why.

Can you try installing it with `pip install path/to/directory`?

**Comment by matiscke** [comment]
didn't work either:
"""pip install .
Processing /Users/schlecker/repos/scan_astro-ph
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: scan-astroph
  Building wheel for scan-astroph (PEP 517) ... done
  Created wheel for scan-astroph: filename=scan_astroph-0.1.dev20+g82d800c-py3-none-any.whl size=6770 sha256=70a8d1c9f69b1bfa106b929ddf3d8c940a8235e3425af8c2c96859be7eb0d9eb
  Stored in directory: /Users/schlecker/Library/Caches/pip/wheels/09/e2/5d/ba521792e7509f435320220d2998b835404cd53fc392f8671a
Successfully built scan-astroph
Installing collected packages: scan-astroph
  Attempting uninstall: scan-astroph
    Found existing installation: scan-astroph 0.1.dev20+g82d800c
    Uninstalling scan-astroph-0.1.dev20+g82d800c:
      Successfully uninstalled scan-astroph-0.1.dev20+g82d800c
Successfully installed scan-astroph-0.1.dev20+g82d800c
Traceback (most recent call last):
  File "/Users/schlecker/opt/anaconda3/bin/pip", line 10, in <module>
    sys.exit(main())
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 117, in main
    return self._main(args)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 261, in _main
    self.handle_pip_version_check(options)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 147, in handle_pip_version_check
    session = self._build_session(
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
    session = PipSession(
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/network/session.py", line 248, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/network/session.py", line 158, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 668, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/Users/schlecker/opt/anaconda3/lib/python3.8/site-packages/scan_astroph-0.1.dev20+g82d800c-py3.8.egg'
"""

**Comment by Simske** [comment]
I will look into it

**Comment by Simske** [comment]
So I think I fixed the problems:
Python packaging is kind of a mess, so I missed something in `setup.py` (which is actually redundant, we could remove it and installation with pip would still work. I put it in for compatibility reasons). Now everything should work.

Your second problem is probably caused by the failed installation, just uninstall with `pip uninstall scan_astroph` and try again.

The "editable" mode of pip is also very useful for development (`pip install -e path/to/package`), with this the package is directly run from the development directory.

**Review by matiscke — APPROVED** [review]
`pip install .` -> works
`python setup.py install` -> works

works like a charm! Ready to merge this PR. 

As @Simske has pointed out in https://github.com/matiscke/scan_astro-ph/issues/8,  with _scan_astro-ph_ available from the whole filesystem we would gain much from having the keyword files available, too. This should be discussed in https://github.com/matiscke/scan_astro-ph/issues/8.

**Comment by Simske** [comment]
> As @Simske has pointed out in #8, with _scan_astro-ph_ available from the whole filesystem we would gain much from having the keyword files available, too. This should be discussed in #8.
I agree. One thing we should also discuss, is which entrypoints should stay enabled. Currently we have multiple aliases active, I think we should reduce this to only one.
Currently active are:
- `scan_astro-ph`
- `scan_astroph`
- `astroph-scan`
The first one matches with the project name, but not with the Python package name (as no underscores are allowed in package names).

The entrypoint for the wordcounter should be the chosen from above with `.wordcounter` appended (like `scan_astroph.wordcounter`).

**Comment by matiscke** [comment]
not sure if this is an issue but I noticed that now that the project is organized in a python package, executing `scan_astroph.py` directly doesn't work anymore.

```
Traceback (most recent call last):
  File "/Users/schlecker/repos/scan_astro-ph/scan_astroph/scan_astroph.py", line 6, in <module>
    from .keywords import TITLE_KEYWORDS, AUTHORS
ImportError: attempted relative import with no known parent package
```

**Comment by Simske** [comment]
Yes, this is true and kind of expected. In my refactor the `scan_astroph.py` file is even completely gone, because I distributed the functions into more descriptive modules.

I don't think it is necessary to run it directly, and for development you should install the package in editable mode.
Pip then creates a link to the working directory instead of copying the package files into the install location. This way the most recent source files are used without having to reinstall after every change.
You can install in editable mode with: `pip install -e /path/to/package` or `python setup.py develop`

**Pull request merged**
